### ISSUE TITLE
Fund Descriptions in Travel Request

### ISSUE THREAD

**Issue by kellanna** [ColoradoEnergyOffice/CEO-Database#2]
Michael Turner was attempting to submit a travel request for an Agriculture conference. When he clicked, "Fund Description" his only option was EPC. When I (Anna) went in to edit his request for him, there were 0 options for Fund Description. His requested has since been deleted, since he realized it was a duplicate. 

His options in "payment request" are fine.

**Comment by ryharry** [comment]
@kellanna, It looks like the "Active" and "Travel" fields on the COA table are the issue. Each COA element needs to be both "True" for Active and "Yes" for Travel in order to use it for travel. There were a few records which did not have anything selected for the Travel field; I fixed these. @pjjohnsonceo can you go into the COA and make sure the Active and Travel fields accurately reflect each funding source? Thanks!

**Comment by pjjohnsonceo** [comment]
Went through and updated the COA table. There were still records that didn't have anything selected for the Travel field, and it looks like a couple more record duplications and potentially a deletion? Anyway things should work, at least for now. Don't want to close the issue til we have confirmation.
